### ISSUE TITLE
gnome-shell freezes after clicking on notifications

### ISSUE THREAD

**Issue by dengelt** [Ippytraxx/gnome-twitch#75] opened 2016-02-14 22:53 UTC
When I click on a notification that tells me that one of my 'favorited' streamers has gone online, gnome-shell freezes. The audio of the stream is still running in the background, I can still move the mouse, but the rest is frozen. No segfault happens at neither gnome-shell nor gnome-twitch, but gnome-shell has these 3 error messages:

```
(gnome-shell:13521): GLib-GIO-CRITICAL **: g_dbus_connection_signal_subscribe: assertion 'object_path == NULL || g_variant_is_object_path (object_path)' failed
(gnome-shell:13521): GLib-GIO-CRITICAL **: g_dbus_connection_signal_subscribe: assertion 'object_path == NULL || g_variant_is_object_path (object_path)' failed
(gnome-shell:13521): GLib-GIO-CRITICAL **: g_dbus_connection_call_internal: assertion 'object_path != NULL && g_variant_is_object_path (object_path)' failed
```

This also happens when there is no stream running. It could be a bug in gnome-shell, but since this is the only application where it happened to me, I suspect it is in gnome-twitch.

To get the error messages I set up two TTYs with the following environment variables: 

```
gnome_session=$(pgrep -u $USER gnome-session)
export $(sed 's/\o000/\n/g;' < /proc/$gnome_session/environ | grep DISPLAY)
export $(sed 's/\o000/\n/g;' < /proc/$gnome_session/environ | grep XAUTHORITY)
export $(sed 's/\o000/\n/g;' < /proc/$gnome_session/environ | grep DBUS_SESSION_BUS_ADDRESS)
```

In one of the TTYs I then ran gnome-shell via gdb (`gdb --args gnome-shell --replace`), and in the other gnome-twitch (`gdb gnome-twitch`). 

Please tell me if I can do anything else to provide more information. I tested this on the develop branch.

**Comment by dchristidis** [comment] 2016-02-15 14:02
I can confirm this bug. However, I think it would be useful to report it to GNOME Bugzilla too. A faulty application should not freeze gnome-shell.

**Comment by Ippytraxx** [comment] 2016-02-15 17:53
Yep I think this can be fixed pretty easily by just setting the default action. Obviously GNOME by default expects some DBus route when the notification is clicked but doesn't find one.

**Comment by hadess** [comment] 2016-03-02 10:37
As @dchristidis said, this is a GNOME bug, though it's also triggered by a gnome-twitch bug.

**Comment by Ippytraxx** [comment] 2016-04-07 18:34
I finally figured it out. Seems like application-ids that don't start with `org` seem to cause this, maybe because someone hard coded it into GNOME Shell. 

I would go post a patch myself, but I don't have the time to go start trawling through their code so I think the easiest fix is to just the application id to something starting with org... I'll do this in some 0.2.x release.

**Comment by hadess** [comment] 2016-04-07 23:07
Pretty sure your root-causing is wrong.

You can check if this patch would help:
https://bugzilla.gnome.org/show_bug.cgi?id=764754

By changing the application-id to "com.gnome_twitch.app"

**Comment by Ippytraxx** [comment] 2016-04-07 23:26
Ok that explains it, I was using `org.gnome.twitch` like other GNOME apps and just assumed it must be the `org`because according to https://developer.gnome.org/gio/unstable/GApplication.html#g-application-id-is-valid app ids are allowed to have hyphens in them.

**Comment by hadess** [comment] 2016-04-08 00:16
They're allowed, but gnome-shell and GLib have different ideas on how you get from the D-Bus name to the D-Bus path. Let's see what happens on the upstream bug.

**Comment by hadess** [comment] 2016-05-09 09:43
This should be fixed in glib now.

**Comment by Ippytraxx** [comment] 2016-05-15 12:53
Great! I'll be able to re-enable notifications again.

**Comment by Ippytraxx** [comment] 2016-08-03 20:09
Continuing this in #141

**Closed by Ippytraxx** 2016-08-03 20:09 UTC
Labels: bug
