### ISSUE TITLE
No channels thumbnails

### ISSUE THREAD

**Issue by terzag** [Ippytraxx/gnome-twitch#113] opened 2016-04-12 20:34 UTC
Got an update of Gnome-Twitch tomorrow, I think it was from WebUpd8's PPA and it's now at version 0.2.0 (not sure it's the latest version).

On Ubuntu Mate 15.10, I have no visual preview / thumbnail of the channels, it's all grey on grey and a darker box when hovering on one. I've put a screenshot there illustrating the problem: http://pix.toile-libre.org/?img=1460493177.jpg

It worked fine in the previous version (from the official PPA, I think it was 0.1.0).

**Comment by Ippytraxx** [comment] 2016-04-12 21:06
Hmm this is very wierd. I just tried the PPA on a fresh Ubuntu Mate 15.10 VM and it worked fine. Any output when you run it from console?

**Comment by terzag** [comment] 2016-04-12 21:13
Didn't think about it but this doesn't look like useful information:
```
[21:09:43] GNOME-Twitch - Message : "{GtApp} Loading chat settings"
[21:09:44] GNOME-Twitch - Message : "{GtApp} Activate"
```
(That's all I get when starting it.)

I was thinking that maybe I'm missing the lib used to create the thumbnails or something like that. My installation isn't the most clean.

**Comment by Ippytraxx** [comment] 2016-04-12 21:14
What GTK+ version do you have?

**Comment by terzag** [comment] 2016-04-12 21:15
How would I check that?

**Comment by Ippytraxx** [comment] 2016-04-12 21:19
Try `dpkg -l libgtk-3-0`

**Comment by terzag** [comment] 2016-04-12 21:25
Here we go for a long log: http://pastebin.com/B1KG2CFE

As for libgtk-3-0, I get the following:
```
||/ Nom                         Version            Architecture       Description
+++-===========================-==================-==================-============================================================
ii  libgtk-3-0:amd64            3.16.7-0ubuntu3    amd64              GTK+ graphical user interface library
rc  libgtk-3-0:i386             3.14.13-0ubuntu1   i386               GTK+ graphical user interface library
```
Not sure why the 32-bit version is older. Not sure if "rc" means it's installed or not either.

**Comment by Ippytraxx** [comment] 2016-04-12 21:32
Yeah nothing in the log unfortunately. I think something is going on here with your GTK+ install. I'm not an Ubuntu user but it's wierd why you have/had an i386 version of it and then all of a sudden changed to a amd64 version of it? 

Not much has changed between 0.1.0 and 0.2.0 when it comes to the channels views so I'm pretty baffled to be honest especially if everything else works.

Couple more questions then:

* Does 0.1.0 still work?
* Do thumbnails show up anywhere else, like favourites, searches, for games, etc?

**Comment by terzag** [comment] 2016-04-12 21:41
Just removed the Gtk3 32-bit package. Not sure where it came from but it seemed tied to libmirclient8, which seems to be the Mir display server from Ubuntu (my initial installation was a standard Ubuntu, not Mate).

Anyway, no change with Gnome-Twitch afterwards. And I have no thumbnails anywhere in the software. I'll downgrade to 0.1.0 to check its behaviour.

**Comment by dengelt** [comment] 2016-04-12 21:44
The 'rc' of dpkg means it is removed, but config files are still present. This shouldn't break anything normally though.

**Comment by terzag** [comment] 2016-04-12 21:44
Ok, now that's weird: 0.1.0 doesn't display thumbnails anymore either. It worked fine beforehand.

**Comment by Ippytraxx** [comment] 2016-04-12 21:46
Yeah try to recall if you upgraded any significant packages or changed anything in the time between 0.1.0 working and you installing 0.2.0? I'm confident now that this at least isn't something in GT (phweph).

**Comment by terzag** [comment] 2016-04-12 21:49
Lats time I used v 0.1.0 was yesterday I think. And I got the 0.2.0 update this morning. I don't remember updating important packages at the same time.

**Comment by dengelt** [comment] 2016-04-12 21:52
Pagacke upgrade logs are in `/var/log/apt/history.log`, that might give you some hints.

**Comment by Ippytraxx** [comment] 2016-04-12 21:58
Well without any error or other major signs I can't really tell what the problem is, BabyRage. Best bet is to try get a clean install and see if the problem still persists.

**Comment by terzag** [comment] 2016-04-12 22:18
I've found the origin of the issue. It's... the Gtk theme I've been starting using recently.

That's unexpected.

**Comment by Ippytraxx** [comment] 2016-04-12 22:20
That's very weird indeed lol. May I ask what GTK theme it was?

**Comment by terzag** [comment] 2016-04-12 22:29
Ultra-Flat (http://gnome-look.org/content/show.php/Ultra-Flat?content=167473), which is based on Numix. Numix works fine with Gnome-Twitch, though.

I guess it defines a CSS class corresponding to the thumbnails in Gnome-Twitch and hides it or something like that.

I don't know anything about Gtk but I know about CSS. Do you know the name of the widget/class/whatever you use for the thumbnails in GT so I can try to relate it to the CSS class and fix the theme?

**Comment by Ippytraxx** [comment] 2016-04-12 22:38
All CSS is here https://github.com/Ippytraxx/gnome-twitch/blob/95a34c03283ffd1cb0c41c308493df689e53a3c5/data/gnome-twitch-style.css (latest commit is for GTK+-3.20 only) but there is nothing in the CSS file that changes anything about the thumbnail though. 

The widget class however is GtkImage and the CSS tree is something like:
`(top parent) GtkFlowBoxChild > GtkBox > GtkStack > GtkEventBox > GtkOverlay > GtkImage (thumbnail)`

**Comment by terzag** [comment] 2016-04-12 22:39
Thanks, I'll try to sort this out tomorrow.

**Comment by dengelt** [comment] 2016-04-13 06:15
@Ippytraxx does that mean that the latest commits will only work with versions 3.20 and higher of GTK+? If so, the dependency list in the README.md should be updated.

**Comment by terzag** [comment] 2016-04-13 09:30
Ok, I managed to track the issue down to that following bit of CSS in the theme:
```
GtkEventBox {
    background-color: @theme_bg_color;
}
```
Now, as I don't know about Gtk, I'm not sure if it's a Gnome-Twitch issue (i.e. you're using the wrong widget or something as it's a valid thing themes designers would change and the problem might occur with other themes) or the theme itself (i.e. this is a value that should never been overwritten in themes and it can break other apps).

Any idea about this? i'll try to get in touch with the theme designer to report the problem.

**Comment by Ippytraxx** [comment] 2016-04-14 17:44
I don't think its meant to have a background set. GtkEventBox is just a transparent container that catches events for widgets that don't do it themselves.

**Comment by terzag** [comment] 2016-04-14 17:48
Ok. Out of curiosity, il you set it to transparent in the CSS file of Gnome-Twitch (eventually as "!important"), will it be overwritten by the desktop theme rules or will it be used and fix the problem?

I've fixed the theme on my side and sent a message to the author but just in case this kind of rule is used by other themes...

**Comment by Ippytraxx** [comment] 2016-04-30 13:10
@terzag Has this been fixed now?

All CSS from `gnome-twitch.css` is loaded with `APPLICATION` priority which is higher than `THEME` priority, so yes I could force it to be transparent but I'd rather not.

**Comment by terzag** [comment] 2016-04-30 13:24
Well, I've sent a message to the theme author through gnome-look.org but didn't get any answer from him.

**Comment by Ippytraxx** [comment] 2016-08-03 20:05
Closing this for now as it's a bug from an external component, hopefully it's fixed now ;)

**Closed by Ippytraxx** 2016-08-03 20:05 UTC
Labels: bug, ui

**Comment by tiendongpro9x11** [comment] 2017-05-13 18:21
try: sudo apt-get dist-upgrade
