### ISSUE TITLE
GNOME Twitch is unable to find some channels

### ISSUE THREAD

**Issue by terzag** [Ippytraxx/gnome-twitch#87] opened 2016-03-21 19:35 UTC
Using version 0.1.0-5 from the official PPA (not sure it's up-to-date, though) on Ubuntu "Wily" 15.10.

For some reason, GNOME Twitch is unable to find some channels. I follow some of the channels from GamingLive, a french network that has multiple ones on Twitch. When they're live, some of them don't show up in the search while others sometimes do. At the moment I'm typing this report, 3 out of their 7 channels are live and are not found by GT; a few days ago, at least 4 were live and GT was able to find 2 of them. Not sure they're random.

**Comment by dengelt** [comment] 2016-03-21 20:09
I just tested this on the latest commit of the development branch, and I can confirm that the channel search behaves somewhat weird. When I tested this, the channel `gaminglive_dota2` was online, but never found in any of the following queries.

When I searched for "gaming", it found channels with "gaming" either in the name or in the game title (e.g. "Gaming Talk Show"), but also some other channels. Searches for "gamingl" up to "gaminglive_" yielded no results. Searches from "gaminglive_d" to "gaminglive_dota2" seemed to yield the combined results of the terms before and after the underscore, as I noticed by trying similar queries.

**Comment by Ippytraxx** [comment] 2016-03-21 20:35
I fixed #59 a while ago when a user was having similar issues but the PPA doesn't have that yet. But for the develop branch not to work is strange. When is the channel usually live so I can try debug it?

**Comment by dengelt** [comment] 2016-03-21 21:03
The channel is online right now, but I don't know if that is it's usual time. 

What I have noticed now is that when I search for a stream in the browser (chromium to be precise), I usually find (at least) two links for a channel that is live, one to the profile (twitch.tv/CHANNELNAME/profile) and one to the channel itself (twitch.tv/CHANNELNAME). But for the channel `gaminglive_dota2`, I only find the link to the profile, even though the channel is online (It says so in the profile and I can watch the stream in chromium). So it seams the problem is on Twitchs end, since the direct search result for the channel is also missing.

**Comment by Ippytraxx** [comment] 2016-03-21 21:34
Yeah I noticed this to. Unfortunately Twitch's API isn't know to be exactly reliable or consistent... I'll be adding a option soon to be able to add watch streams directly by pasting the Twitch URL or channel name which will hopefully overcome this problem when it arises.

**Comment by terzag** [comment] 2016-03-21 22:25
I'm not sure when these channels are live exactly (especially as I only really follow two of the seven) but before I posted the report, I searched for "gaminglive" on the Twitch website and it found all of them, either offline or online. But I think there were only links to the profiles, not sure they were reported as live on the search results page (are they supposed to? I don't really use search on Twitch).

An option to add a channel through its name/url would be great.

**Comment by dengelt** [comment] 2016-03-21 23:42
If you add such an option, could you also add a command line argument for it, so one could call gnome-twitch like `gnome-twitch --channel-name NAME` or `gnome-twitch --channel-url URL` to go directly to the channel?

**Comment by CubeTheThird** [comment] 2016-04-07 23:31
From what I can tell, searches are case sensitive. Might this be the issue?

**Comment by Ippytraxx** [comment] 2016-04-07 23:45
Possibly, I don't conduct any searching/filtering myself. Whatever you type in is what is sent to the Twitch API, so it's up to Twitch whether they do case sensitive searches or not. Basically Twitch's API is just broken and this is just a symptom of it.

**Comment by terzag** [comment] 2016-04-08 07:31
I'm pretty sure I've tried to type them with the right case when I saw I didn't find them. But since then, I've been able to find the GamingLive channels and add them to my favs, so it's pretty weird.

BTW, I figured something when looking for another channel: Gnome Twitch only checks for live streams, right? it doesn't look for channels that can be offline? Would it be possible to search for channels so to find everything that fits, live or not?

**Comment by Ippytraxx** [comment] 2016-04-08 09:41
Yes that is what I plan to do. Unfortunately the Twitch API has split itself up into streams and channels therefore I would have to make multiple requests to check online and offline channels. That's why I haven't implemented it yet plus viewing offline channels currently isn't so useful anyways.

I'm thinking once I implement things like Twitch follows and VODs then seeing offline channels will be way more useful so I'll be doing it then.

**Comment by Ippytraxx** [comment] 2016-08-03 19:58
Closing for now as I couldn't find any concrete reason for this happening, but it's most likely from Twitch's side.

**Closed by Ippytraxx** 2016-08-03 19:58 UTC
Labels: API, bug, wontfix
